### ISSUE TITLE
CMakeList.txt における message の使い方について

### ISSUE THREAD

**Issue by equal-l2** [yossi-tahara/Theolizer#10]
sourceフォルダ内のいくつかのCMakeList.txtで、`message(SEND_ERROR "~")`や`message(ERROR "~")`という記述があります。

前者について、軽微なエラーで使われるのはいいと思うのですが、「必要なライブラリが存在しない」とか「引数で与えられた設定が間違っている」などにおいては代わりに`message(FATAL_ERROR "~")`を使ったほうがいいのではないでしょうか。

後者について、CMake公式のドキュメントを読んでも`ERROR`というオプションはないようです。
これも`SEND_ERROR`や`FATAL_ERROR`に変えたほうが良いのではないでしょうか。

参考 : [message — CMake 3.5.2 Documentation](https://cmake.org/cmake/help/v3.5/command/message.html)

**Comment by yossi-tahara** [comment]
指摘ありとうございます。

前者はあまり深く考えずにSEND_ERRORを使ってました。検討してみます。
後者は単純ミスです。修正します。

**Comment by yossi-tahara** [comment]
SEND_ERROR検討しました。

まず、現在のビルド・システムの構造はざっくり以下の通りです。

  - **Theolizer本体用**
build_tools/toolsにあるcmakeスクリプト（zz_prepare.cmakeとzz_process.cmak）から、execute_processでsourceのCMakeLists.txtによるビルド・構築とビルド処理を呼び出す

  - **boostとllvmビルド用***
build_tools/boost_buildとbuild_llvmにあるcmakeスクリプト（eprepare.cmake）から、execute_processで各々のビルドに必要なcmakeスクリプトやその他のコマンドを呼び出す

各cmakeスクリプトは、複数の構成（32bit/64bit, Debug/Release等）によるビルドを連続して呼び出し、昼休み前や帰宅前に仕込んで、後で結果を見ることを想定しています。
execute_process内の処理をFATAL_ERRORで止めても、後続の構成のビルドは継続されますが、ログに全てのエラーが記載されていた方が開発効率は良いと思います。
また、**build_tools**のルート側に属するスクリプトを途中で停止するとかなり辛いです。（現在のTheolizerでも1.5時間、llvmは一晩近く掛かります。）
execute_processを経由する場合は途中でFATAL_ERRORで止めても後続の構成のビルドは継続されますが、FATAL_ERRORで止めなければならない部分はないように感じます。

従って、ビルド処理をできるだけ継続するため、原則としてこのままSEND_ERRORを使おうと思います。
ですが、もし、ここはFATAL_ERRORで中断した方が良い場所があれば、ご指摘下さい。
SEND_ERRORを使用している箇所はざっくり下記の通りです。

**source**

|使っている場所|その内容|
|---------------------|----------|
|CMakeLists.txt|Theolizer本体のビルド・バラメータ・チェック|
|document/CMakeLists.txt|ドキュメントのビルド・バラメータ・チェック|
|reference_and_test/CMakeLists.txtの71行と83行|テストのCMakeLists.txtバグ検出|
|reference_and_test/CMakeLists.txtのその他|テストのビルド・バラメータ・チェック|

**build_tools**

|使っている場所|その内容|
|---------------------|----------|
|tools/zz_prepare.cmakeの214行と225行|現処理を中断し、後続の構成から再開制御|
|tools/zz_prepare.cmakeのその他|ビルド・パラメータ・チェック|
|tools/zz_process.cmakeの194行|現処理を中断し、後続の構成から再開制御|
|tools/zz_process.cmakeの325行|エラー発生を呼び出し元へ中継|
|boostとllvmのprepare.cmakeの130行|エラー発生を呼び出し元へ中継|
|boostとllvmのprepare.cmakeのその他|ビルド・パラメータ・チェック|

**Comment by yossi-tahara** [comment]
時間が経過しましたので、一旦クローズします。
現状の使い方に対して、変更した方が好ましい点が見つかりましたら、再オープンをお願いします。
