### ISSUE TITLE
LLVMやBoostのダウンロード~ビルドまでの自動化

### ISSUE THREAD

**Issue by equal-l2** [yossi-tahara/Theolizer#11]
sourcesフォルダの方でも依存ソフトウェアのダウンロード(できればビルドまで)の自動化が欲しいです。

実例を挙げますと、[neovim](https://github.com/neovim/neovim)ではビルド時に依存ソフトウェアを自動でダウンロード&ビルドしています。

**Comment by yossi-tahara** [comment]
LLVMとboostのビルド時の自動ダウンロード対応した時に検討したのですが、断念しました。

自動化する場合、ダウンロードやビルドが完了している部分についてスキップする機能の実装が欲しいと思います。特にLLVMはダウンロードとビルドに掛かる時間が大きいので必須と思います。

boostならビルド時間が短いので、それらの機能の実装やリリース時のデグレード防止テストを行うことも可能です。
しかし、LLVMでそれらの機能をデバッグし、リリースの度にデグレード防止テストを実施するのは現実的ではなく、Theolizerのビルド・システムに直接組み込むのは避けたいです。また、分けておけば、Theolizerのビルド・システムの改変でLLVMのビルド失敗に至る可能性はほぼ０です。ここに頼りたいです。

**Comment by equal-l2** [comment]
事情はよく分かりました。

**Comment by yossi-tahara** [comment]
時間経過したので一旦クローズします。
この機能があるとかなり好ましい状況が見つかったら、そのシナリオと共に再オープンお願い致します。
