### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by equal-l2** [yossi-tahara/Theolizer#14]
ところどころ、`COMPLIER`という記述があるのですが、`COMPILER`の誤字ではないでしょうか?

(Pull Requestすべきではあるのですが手元でビルドが通らずコミットできないため、Issueにて失礼します)

**Comment by yossi-tahara** [comment]
ああ、その通りです。
どうも指の動きが悪いのかキーボードの応答が悪いのか、Iの入力がワンテンポ遅れてしまうのです。
THEOLIZERが良くTHEOLZIERになってしまいます。こちらはコンパイルエラーが出てくれるので修正できるのですが。

後ほど、修正します。ご指摘ありがとうございます。

**Comment by yossi-tahara** [comment]
修正してプッシュしました。
