### ISSUE TITLE
コミット時フックの見直し

### ISSUE THREAD

**Issue by equal-l2** [yossi-tahara/Theolizer#17]
現在、コミットする際には、ビルド完了後に得られるハッシュ値が必要です。

この状況においては、現在ビルドが通らない環境からのPull Requestによる貢献が出来ません。
私もそのような環境にあります。
この環境から問題解決をするには、Issueを通じてオーナーに任せるしかありません。

コントリビューターとしては、外野から意見ばかり言うのは心苦しく思います。
オーナー側としてもコードを(些細な誤字脱字等の修正でも)すべてご自分で書くというのは負担が大きいのではないでしょうか。

CIサービスを利用すれば、Pull Requestを自動でビルド、テストすることも出来ます。
これによって、動作しない状態のコミットが混入することは防げるかと思います。

ご一考よろしくお願いします。

**Comment by yossi-tahara** [comment]
なるほど。そのような問題が発生するのですね。
現在の機能は私自身がビルドし忘れることの防止用でもあるので、何か考えてみます。

**Comment by yossi-tahara** [comment]
思い出しました。#6が元々のIssueに当たりますので、#6を再オープンし、当Issueをクローズします。
