### ISSUE TITLE
cmakeではsetよりoptionを使う

### ISSUE THREAD

**Issue by yumetodo** [yossi-tahara/Theolizer#2]
http://doc.theolizer.com/html/_how_to_build_theolizer.html#HowToBuildLibrary121

によればcmakeファイルを書き換えろとのことだが、そういうのはoptionにするべきではないのか

**Comment by yossi-tahara** [comment]
ご意見、ありがとう。

今回のような使い方の場合、同じコマンドを複数回発行することがほとんどと思います。
CMakeジェネレーションでさえ、混乱した時はビルド・フォルダを全部削除して同じコマンドを叩くと思います。
また、旧プロジェクトのビルドが必要な時もあると思います。
そのような時のために、別の何処かにoptionを記録しておくより、ビルド・スクリプト内に記録しておいた方が使い勝手は良いと考えています。

個人の環境に合わせた設定をGitHubに登録するのは如何なものか？と言う話があると思います。
登録するものはできるだけ多くの人の環境で使えるデフォルト設定にしたいと思っています。
この設定は他の方の見解も頂いて、今後練り上げていく必要があります。

**Comment by yumetodo** [comment]
どのみちsetしている部分を書き換えてくれとドキュメントに今書いているのですから、それならoptionにしましょうよ、という話です。その時点で

> ビルド・スクリプト内に記録しておいた方が使い勝手は良いと考えています。

は関係ありません。

---

> 別の何処かにoptionを記録しておくより

いや、そのためのデフォルト値では・・・

またOSに応じてoptionの**デフォルト値を切り替える**こともできなくはないので将来的にはcmakeをOSごとにわけずに一つにまとめることでメンテナンス性が上がるのではないかと思います。

**Comment by yossi-tahara** [comment]
> それならoptionにしましょうよ、という話です。

option指定するメリットが分かりません。でも、実は何か私が想定できていない場面で困っているのでは？
CMakeは普通はCMakeLists.txtを使い、ジェネレータ等をoption指定しますね。そのような使い方をしたいということではないでしょうか？

実は、TheolizerもCMakeLists.txtを普通に用意しています。他の環境への移植をこんなに速くトライしてくれる人が現れると想定できていなかったので、これを使うために必要な解説をしていませんでした。

sourceの下にCMakeLists.txtがあります。これは通常のCMakeLists.txt的な使い方をしています。
optionは下記です。

| 変数名 | 設定内容 | 備考 |
| --- | --- | --- |
| CMAKE_INSTALL_PREFIX | Theolizerをインストールするフォルダのフルパス名 | 必須 |
| LIB_TYPE | ビルドするライブラリ・タイプ | StaticWithBoost, Static, Sharedのどれか。省略時StaticWithBoost |
| BOOST_ROOT | 使用するboostのインストール先フォルダのフルパス名 | 必須 |
| LLVM_ROOT | 使用するllvmのインストール先フォルダのフルパス名 | ドライバをビルドする時のみ指定する |
| BUILD_DOCUMENT | Doxytenドキュメント生成指定 | TRUE, FALSEのどちらか。省略時FALSE |
| CMAKE_BUILD_TYPE | ビルドするConfig | Debug, Release, 無指定のどれか。msvcは無指定。gccはDebug or Release |

例えば、sourceと並ぶ位置にbuild_mingwフォルダを置き、その中で下記コマンドを実行るとMinGW用にコンフィグできます。

```
> CMake -G "MinGW Makefiles" ../source "-DCMAKE_INSTALL_PREFIX=C:/Theolizer" "-DLIB_TYPE=Static" "-DBOOST_ROOT=C:/Boost64" "-DLLVM_ROOT=C:\llvm380\mingw540x64-Release" -DCMAKE_BUILD_TYPE=Release
```

下記のターゲットが有用と思います。

| ターゲット名 | 意味 |
| --- | --- |
| ShortTest | ライブラリのビルドとテスト |
| LongTest | ドライバのビルドとテスト |
| FullTest | ライブラリのビルドとテスト<br>ドライバのビルドとテスト<br>ドキュメントのビルド<br>Theolizerのインストール<br>インストール確認のためのビルド・テスト |

---

【ちなみに】
theolizerは複数のコンパイラに対応していますし、32/64ビットビルド等も必要です。しかし、CMakeLists.txtで複数のジェネレータでの生成はできないように思います。
そこで、当初はbatファイルで必要なフォルダを準備してCMake -G "xxx"を呼び出してプロジェクト生成し、各フォルダ毎にビルドしてインストールして．．．を自動化してました。
それをlinuxでもやる必要があるのですが、改めてbashで作ると同じことを異なる文法で記述することになりメンテナンスがきついです。
しかし、cmakeのスクリプト・モードを使えばマルチ・プラットフォームなのでまとめて作れることが判ったのでこれを使うことにしました。
つまり、一般にはbatやshで記述する部分を、cmakeで記述したものが、theolizerのビルド・システムに登録されている*.cmakeスクリプト・ファイル群です。

複雑な部分はprepare.cmakeやprocess.cmakeへ押し込め、設定部だけを取り出したものがlinux.cmakeとwindows.cmakeです。
この中のbuild_by_msvc()やbuild_by_gcc()の取捨選択も含めて全てのパラメータを手で直接option指定することは、事実上無理と思います。
結局、これくらい複雑になると、どこかのファイルに記述せざる得ません。その記述先を外部のshやbatで書くのではなくwindows.cmakeやlinux.cmakeに書くようにしました。
これらは、そのような位置づけなのです。

**Comment by yumetodo** [comment]
> でも、実は何か私が想定できていない場面で困っているのでは？

いや、いまいち私の頭が回っていなかったようです。

一旦closeして何かあったら別途報告します。

**Comment by yossi-tahara** [comment]
了解です。
