### ISSUE TITLE
Travis CIのキャッシュの有効化

### ISSUE THREAD

**Issue by yossi-tahara** [yossi-tahara/Theolizer#21]
[ここ](https://github.com/yossi-tahara/Theolizer/issues/15#issuecomment-273665754)からの分岐です。
現在、addonsのインストールとboostのビルドにどちらも2 ～3分かかってます。
この2つは常に同じものなのでできればキャッシュを有効にする方向で検討します。

**Comment by equal-l2** [comment]
https://docs.travis-ci.com/user/caching/#Things-not-to-cache
これから類推するとAPTパッケージはキャッシュするべきでないように思われます。

Boostはキャッシュしておいて差し支えないと思います。

**Comment by yossi-tahara** [comment]
なるほど。
あ、でも今[こんな情報](http://qiita.com/oh_rusty_nail/items/ffffeef8fb92b458a2b6)をみつけました。
一行追加するだけなので効果の程は不明ですが、やってみます。

今、前回のビルドがFAILしてました。前々回と同じもの（[skip ci]するべきだった）なのでタイムアウトと思われます。
タイムアウトを40分に伸ばしてみますが、そろそろ限界の筈なので頭が痛い。
後日、boostのキャッシュにも挑戦します。

**Comment by equal-l2** [comment]
APTのキャッシュ機能は動かないようです。
https://github.com/travis-ci/travis-ci/issues/5876#issuecomment-207661127

**Comment by yossi-tahara** [comment]
残念。APTのキャッシュ指示は削除します。

今回のTheolizerのビルドとテストはちょうど30分でした。
今後のテストの追加に伴うテスト時間の増大を考えると何か対策が必要そうです。
自動テストなので節約は考えない組み合せを単純生成しているため、少し工夫する方向で考えます。

**Comment by yossi-tahara** [comment]
boostのキャッシュ完了しました。
Travis CIについてキャッシュできるものは他にないのでこれでクローズします。
