### ISSUE TITLE
LLVMやBoostのソースコードを自動でダウンロードする

### ISSUE THREAD

**Issue by equal-l2** [yossi-tahara/Theolizer#3]
現在Theolizerをビルドするにあたっては、LLVMやBoostのソースコードをユーザーがダウンロードする必要があります。
これをビルド時に自動でダウンロードするようには出来ないでしょうか?

CMakeにはファイルをダウンロードするコマンドがあるようです。
https://cmake.org/cmake/help/v3.0/command/file.html?highlight=DOWNLOAD

また、関係あるかわかりませんが、LLVMの「NCSA/イリノイ大学オープンソースライセンス」およびBoostの「Boostソフトウェアライセンス」はいずれもGPLと両立できるようです。
https://www.gnu.org/licenses/license-list.ja.html#GPLCompatibleLicenses

**Comment by yossi-tahara** [comment]
お問い合わせ、ありがとうございます。

> 現在Theolizerをビルドするにあたっては、LLVMやBoostのソースコードをユーザーがダウンロードする必要があります。
> これをビルド時に自動でダウンロードするようには出来ないでしょうか?
> CMakeにはファイルをダウンロードするコマンドがあるようです。

おお、その発想はありませんでした。恐らく可能と思います。
llvmのダウンロードは結構面倒ですので用意すると好ましいですね。
折を見て本当に可能か確認し、可能ならば対応したいと思います。
（GitHubのProjectへ登録してみます。初めてなのでミスがあってもご容赦下さい。）

ライセンスはいつも複雑です。
llvmとboostのライセンスは緩いのでソース配布時はGPLv3として配布すれば良い筈ですね。しかし、Theolizerのソースはllvmとboostのソースを含んでいないのでソース配布上はllvmとboostのライセンスは無関係です。
もし、llvmとboostをGPLv3で私が再配布するとそれはそれで手間がかかりますし、ミスが怖いので避けています。

プリビルド版にはllvmとboostのバイナリを含んでいるため、llvmとboostのライセンスに従う必要が有ります。
llvmは使用許諾書の同梱を要求されているのでプリビルド版にはLICENSE.TXTを同梱しています。
boostはバイナリ配布についてはライセンス表示の要求はありませんが、表示しても問題ないと思いますので、LICENSE.TXTを同梱してます。

**Comment by yossi-tahara** [comment]
Projectへ登録し、時間経過したのでCloseします。
また何かあったらReopenして下さい。

**Comment by yossi-tahara** [comment]
対応しました。
ただ、Windows 10上のVirtualBox上のubuntu 16.04上でboostのダウンロードに失敗します。
条件が複雑すぎて追いかけきれないのでずか、CMakeのfile(DOWNLOAD)機能が上記条件でsourceforgeからのダウンロードに対応できていないと思われます。
boostのダウンロードはそれほどたいへんではないので、そのようなケースでは手動で操作して下さい。

equal-l2さん、この内容でよろしいでしょうか?

**Comment by equal-l2** [comment]
手元の環境はmacOSですが、ダウンロードできるのを確認しました。
Ubuntuの件は別途Issueを立てておくとよいかと思います。

**Comment by yossi-tahara** [comment]
確認、ありがとうごさいます。

ubuntuの件は、sourceforgeからのダウンロードができないバグは考えにくいので、恐らくVirtualBoxが絡んでいるのだろうと予想しています。
ご提案の通りIssuesに立てておきます。
